descartes_recupbd:
    resource: "@DescartesRecupbdBundle/Resources/config/routing.yml"
    prefix:   /

descartes_recherche:
    resource: "@DescartesRechercheBundle/Resources/config/routing.yml"
    prefix:   /

descartes_evenement:
    resource: "@DescartesEvenementBundle/Resources/config/routing.yml"
    prefix:   /

descartes_utilisateur:
    resource: "@DescartesUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

_security_login:
    pattern: /loginfb
_security_check:
    pattern:  /loginfb_check


fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /utilisateur/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /utilisateur/profile
