parameters:
#    descartes_utilisateur.example.class: Descartes\UtilisateurBundle\Example

services:
#    descartes_utilisateur.example:
#        class: %descartes_utilisateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
